### PR TITLE
Prodcons summary report

### PR DESCRIPTION
**Pull request by mgax**
Fixes https://github.com/eaudeweb/ozone/issues/1427.

* Contains some more refactoring of the prodcons report
* [x] Aggregation by region
  * [x] Aggregate values for prod, cons, and baselines, grouped by region
  * [x] Population aggregated by region
  * [x] Aggregate values for prod, cons, baselines over all the parties
* [x] A5 and NA5 parties aggregated
* [x] A5 and NA5 parties not aggregated

### CODE REVIEW

**Comment by melish** [comment]
TODO: test EU population and per capita consumption (which normally should be calculated vs the entire population of the EU rather than individual parties who have/have not reported).

**Comment by mgax** [comment]
> test EU population and per capita consumption

I've checked: the current formula result matches with the sample report. If I count the EU population as a whole, in the report by region, EU contains countries both in `WEUR` and `EEUR`, so the math gets complicated. I'd leave it as-is for now.

**Comment by melish** [comment]
The %Chng column does not appear anymore in the new version of the old ProdCons vs baseline report

**Comment by melish** [comment]
@mgax See this report for Australia, period C1999.
I think Consumption should appear as N.R. instead of blank. Why is it N.R. only for Production, but not Consumption?

**Pull request merged**
