### PR TITLE
446 refactor tests

### LINKED ISSUE #446: Refactor unit tests to use the client.login method
This will significantly shorten test code and make it all about testing instead of doing boilerplate stuff.

### PR DESCRIPTION
**Pull request by catalinjitea**
closes #446.

### CODE REVIEW

**Comment by sorinstelian** [comment]
LGTM, but I would also like @alexkiro to take a look at this before merging.

**Comment by alexkiro** [comment]
@catalinjitea Looks good to me as well. However, I've added some new tests in #489 for the uploads. They would need changing and some of them are using `LiveServerTestCase` so we would need another base class for them AFAICT. 

Let me know if you want me to change them, would be happy to help :)

**Comment by catalinjitea** [comment]
@alexkiro I see that the tests that are using `LiveServerTestCase` don't use the usual authentication approach, so it should work. I'll let you know if I need any help.

**Comment by sorinstelian** [comment]
One last error:
```
ERROR: ozone.tests.test_uploads (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: ozone.tests.test_uploads
Traceback (most recent call last):
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/python/3.6.3/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/eaudeweb/ozone/ozone/tests/test_uploads.py", line 194, in <module>
    class TestListFiles(BaseSubmissionTest, TestCase):
NameError: name 'TestCase' is not defined
```

**Pull request merged**
