### PR TITLE
Report for "production, import and export"

### PR DESCRIPTION
**Pull request by mgax**
Fixes https://github.com/eaudeweb/ozone/issues/1143

### CODE REVIEW

**Comment by melish** [comment]
@mgax Please check roundings - see 2018 report
http://prntscr.com/q5xxic

**Comment by melish** [comment]
The data should also be filtered by the selected parties, if any. In general, party users should not see unaggregated data of other parties

**Comment by mgax** [comment]
> The data should also be filtered by the selected parties, if any.

Right, fixed.

**Comment by melish** [comment]
- [ ] Values are still not ok, now all values are rounded to the nearest int, which is not correct.
The number of decimals should depend on the annex group and period, see cached property ProdCons.decimals. In general, there should be 2 decimals in most cases, 1 decimal for C/I before 2010 and zero decimals for annex F.
- [ ] Please add group description after the group names (e.g. Hydrochlorofluorocarbons (HCFCs)). Resize the columns (again!) if needed.

**Comment by mgax** [comment]
@melish I've fixed the missing baselines (they were not being calculated, forgot to copy/paste the formula) and the rounding decimal places. Please check again.

**Pull request merged**
