### PR TITLE
Add endpoint for retrieving and updating user details, refs #533

### PR DESCRIPTION
**Pull request by catalinjitea**
Only allow changing name, email, language

### CODE REVIEW

**Comment by alexkiro** [comment]
@catalinjitea maybe it would be cleaner to use the existing view `CurrentUserViewSet` ?

**Comment by catalinjitea** [comment]
> @catalinjitea maybe it would be cleaner to use the existing view `CurrentUserViewSet` ?

@alexkiro I thought about it, but that use `CurrentUserSerializer` which contains some extra information that I'm not sure it serves the purpose.

**Comment by alexkiro** [comment]
> @alexkiro I thought about it, but that use `CurrentUserSerializer` which contains some extra information that I'm not sure it serves the purpose.

I think it might be worth just using adding `language` to `CurrentUserSerializer` and setting anything that shouldn't be updated in the `read_only_fields` tuple. Instead of having 3 separate serializers for the user model.

**Comment by catalinjitea** [comment]
> > @alexkiro I thought about it, but that use `CurrentUserSerializer` which contains some extra information that I'm not sure it serves the purpose.
> 
> I think it might be worth just using adding `language` to `CurrentUserSerializer` and setting anything that shouldn't be updated in the `read_only_fields` tuple. Instead of having 3 separate serializers for the user model.

Thanks for the idea. I'll try that.

**Pull request merged**
